#!/bin/bash
# Generated by gpt-4o on 2024 07 10
# ./convert_png_to_jpg.sh ~/Pictures 85

# Check if the correct number of arguments are provided
if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <directory> <quality>"
  exit 1
fi

# Assign arguments to variables
DIRECTORY=$1
QUALITY=$2

# Check if the quality is a valid number between 0 and 100
if ! [[ "$QUALITY" =~ ^[0-9]+$ ]] || [ "$QUALITY" -lt 0 ] || [ "$QUALITY" -gt 100 ]; then
  echo "Quality must be an integer between 0 and 100."
  exit 1
fi

# Find and convert PNG files to JPG files with the specified quality
find "$DIRECTORY" -type f -name "*.png" | while read -r FILE; do
  # Construct the output file name
  OUTPUT_FILE="${FILE%.png}.jpg"
  echo "Converting $FILE to $OUTPUT_FILE with quality $QUALITY"

  # Convert the PNG file to JPG with the specified quality
  sips -s format jpeg -s formatOptions $QUALITY "$FILE" --out "$OUTPUT_FILE"
  
  # Uncomment the line below to remove the original PNG file after conversion
  # rm "$FILE"
done

echo "Conversion completed."
