/* Generated by gpt-4o on 2024 07 10 */
/* node generate-index.js ../first-last "First Last" */

const fs = require('fs');
const path = require('path');

const [,, folderName, personName] = process.argv;

if (!folderName || !personName) {
  console.error('Please provide both a folder name and a person\'s name.');
  process.exit(1);
}

const templatePath = path.join(__dirname, '_template', 'index.html');

fs.readFile(templatePath, 'utf8', (err, data) => {
  if (err) {
    console.error(`Error reading template file: ${err}`);
    process.exit(1);
  }

  const result = data.replace(/Student Name/g, personName);

  const outputFolderPath = path.join(__dirname, folderName);
  
  if (!fs.existsSync(outputFolderPath)) {
    fs.mkdirSync(outputFolderPath, { recursive: true });
  }

  const outputPath = path.join(outputFolderPath, 'index.html');

  fs.writeFile(outputPath, result, 'utf8', (err) => {
    if (err) {
      console.error(`Error writing new index.html file: ${err}`);
      process.exit(1);
    }

    console.log(`index.html has been created successfully in the folder: ${folderName}`);
  });
});
