#!/bin/sh
# Generated by gpt-4o on 2024 07 10
# Converts all the featured PNG files to JPG files.

find .. -type f -name "featured.png" | while read -r file; do
  parent_dir=$(basename "$(dirname "$file")")
  new_name="${parent_dir}_$(basename "$file")"
  mv "$file" "$(dirname "$file")/$new_name"
done
